kNN BERT baseline for sense disambiguation
Living-with-machines/TargetedSenseDisambiguation pull request #45
Opened 2020-11-10 13:48 UTC by kasparvonbeelen

Implement kNN BERT baseline for sense disambiguation

Closes #44

2020-11-23 19:10 UTC, kasra-hosseini requested changes

2020-11-23 19:13 UTC, kasra-hosseini requested changes
I reviewed the two .py files (classification_utils and bert_nn_demo). Both work and are well-documented. I just made some changes: https://github.com/Living-with-machines/HistoricalDictionaryExpansion/pull/45/commits/13ace7870d4990e206f54ad7b72dcb5974e0b6de and some other minor inline comments.

2020-11-26 18:28 UTC, fedenanni requested changes
All good - only the gitignore needs to be polished - thanks a lot!

2020-11-30 15:33 UTC, fedenanni approved these changes

2020-11-30 16:17 UTC, merged